INSERT INTO THEMATIC_PATH VALUES (1, 'ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING');
INSERT INTO THEMATIC_PATH VALUES (2, 'COMMON MISTAKES');
INSERT INTO THEMATIC_PATH VALUES (3, 'THE BRIGHTER FUTURE OF IT');

INSERT INTO LECTURE VALUES (1, 'WHAT DO WE KNOW ABOUT AI', 1);
INSERT INTO LECTURE VALUES (2, 'THE RISKS', 1);
INSERT INTO LECTURE VALUES (3, 'DIRECTIONS OF THE DEVELOPMENT', 1);

INSERT INTO LECTURE VALUES (4, 'COMMON MISTAKES', 2);
INSERT INTO LECTURE VALUES (5, 'HOW TO AVOID MAKING MISTAKES', 2);
INSERT INTO LECTURE VALUES (6, 'EXERCISES THAT HELPS TO IMPROVE OUR FOCUS', 2);

INSERT INTO LECTURE VALUES (7, 'THE IT MARKET', 3);
INSERT INTO LECTURE VALUES (8, 'NEW TECHNOLOGIES', 3);
INSERT INTO LECTURE VALUES (9, 'THE GROUNDBREAKING TOOLS', 3);

