CREATE TABLE LECTURE (
                         ID INTEGER NOT NULL AUTO_INCREMENT,
                         TITLE VARCHAR(50)  NOT NULL,
                         THEMATIC_PATH_ID VARCHAR  NOT NULL,
                         PRIMARY KEY (ID)
) ;

CREATE TABLE THEMATIC_PATH (
                               ID INT NOT NULL,
                               DESCRIPTION VARCHAR(100)  NOT NULL,
                               PRIMARY KEY (ID)
) ;

CREATE TABLE RESERVATION (
                             ID INT NOT NULL,
                             CUSTOMER_ID INT NOT NULL,
                             LECTURE_ID INT NOT NULL,
                             PRIMARY KEY (ID)
) ;

CREATE TABLE CUSTOMER (
                      ID INT NOT NULL AUTO_INCREMENT,
                      LOGIN VARCHAR(20) NOT NULL,
                      EMAIL VARCHAR(50) NOT NULL,
                      PRIMARY KEY (ID)
) ;

ALTER TABLE LECTURE ADD CONSTRAINT LECTURE_THEMATIC_PATH
    FOREIGN KEY (THEMATIC_PATH_ID)
        REFERENCES THEMATIC_PATH (ID);

ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_LECTURE
    FOREIGN KEY (LECTURE_ID)
        REFERENCES LECTURE (ID);

ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_USER
    FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER (ID);